name: Run Project Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JWT_SECRET: test_secret
  REDIS_HOST: localhost
  REDIS_PORT: 6379

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
